In [1]:
# NumPy kutubxonasini import qilish
import numpy as np

1. NumPy array yaratish

In [2]:
# 1D array yaratish
arr_1d = np.array([1, 2, 3, 4, 5])

# 2D array yaratish
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Faqat 0 lardan iborat array yaratish
zeros_array = np.zeros((3, 4))

# Faqat 1 lardan iborat array yaratish
ones_array = np.ones((2, 3))

# range qiymatlar yaratish
range_array = np.arange(0, 10, 2)

# linspace array yaratish
linspace_array = np.linspace(0, 1, 5)

# Tasodifiy qiymatlar arrayini yaratish
random_array = np.random.rand(3, 3)

# Identifikatsiya matritsasi yaratish
identity_matrix = np.eye(3)

# linscpace arrayni ekranga chiqarish
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

2. Array ustida amallar

In [3]:
# arraylarni bir biriga qo'shish
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result_add = arr1 + arr2

# arraylarni bir-biriga ko'paytirish
result_mul = arr1 * arr2

# matritsalarni metod orqali ko'paytirish
result_dot = np.dot(arr1, arr2)

# arrayning transpose qiymatini hisoblash
arr_transpose = arr1.T

# result_mul natijani ekranga chiqarish
result_mul

array([[ 5, 12],
       [21, 32]])

3. Indekslash va kesish

In [4]:
# 1D array indekslash
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[2])  # chiqish: 3

# 1D array kesish
print(arr_1d[1:4])  # chiqish: [2, 3, 4]

# 2D arrayni indekslash
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d[1, 2])  # chiqish: 6

# 2D array kesib olish
print(arr_2d[:, 1:])

3
[2 3 4]
6
[[2 3]
 [5 6]]


4. Universal funksiyalar

In [5]:
# arrayning har bir elementini kvadrat ildizini hisoblash
arr = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr)

# arrayning har bir elemtini exponenta qiymatini hisoblash
exp_arr = np.exp(arr)

# arrayning har bir qiymati uchun sin() ni hisoblash
sin_arr = np.sin(arr)